"""Supplement datasets.json with missing entries from 4 catalog domains."""
import json
import re

PYTHON = True

def make_id(name):
    s = name.lower().strip()
    s = re.sub(r'[^a-z0-9\s-]', '', s)
    s = re.sub(r'[\s]+', '-', s)
    s = re.sub(r'-+', '-', s)
    return s[:60].strip('-')

# Load existing
with open('C:/DatasetCadaster/datasets.json', 'r', encoding='utf-8') as f:
    data = json.load(f)

existing_names = {d['name'].lower().strip() for d in data}
existing_urls = {d['url'].lower().strip().rstrip('/') for d in data}
existing_ids = {d['id'] for d in data}

def is_dup(name, url):
    n = name.lower().strip() in existing_names
    u = url and url.lower().strip().rstrip('/') in existing_urls
    return n or u

def add(name, url, cat, subcat, scope, country, operator, dtype, sres, tres, tcov, cost, api, proto, fmt, lic, desc, tags):
    if is_dup(name, url):
        return False
    eid = make_id(name)
    if eid in existing_ids:
        eid = eid + '-' + cat[:3]
    existing_ids.add(eid)
    existing_names.add(name.lower().strip())
    if url:
        existing_urls.add(url.lower().strip().rstrip('/'))
    data.append({
        'id': eid, 'name': name, 'url': url, 'category': cat,
        'subcategory': subcat, 'scope': scope, 'country': country,
        'operator': operator, 'dataType': dtype, 'spatialResolution': sres,
        'temporalResolution': tres, 'temporalCoverage': tcov, 'cost': cost,
        'apiSupport': api, 'apiProtocol': proto, 'formats': fmt,
        'license': lic, 'description': desc, 'tags': tags
    })
    return True

added = {'population-urban': 0, 'air-quality': 0, 'ocean-marine': 0, 'admin-boundaries': 0}

# ============ POPULATION / URBAN ============
PU = 'population-urban'
add('GHSL GHS-POP', 'https://ghsl.jrc.ec.europa.eu/', PU, 'population-grid', 'global', None, 'JRC', 'Population grids, built-up surface, settlement', '100m-1km', 'multi-epoch', '1975-2030', 'free', False, None, 'GeoTIFF', 'CC-BY 4.0', 'Global gridded population and built-up area from Landsat/Sentinel + census', ['population','settlement','urban','built-up'])
add('WorldPop', 'https://www.worldpop.org/', PU, 'population-grid', 'global', None, 'Univ. Southampton', 'Population grids with demographics', '100m', 'annual', '2000-2020', 'free', True, 'REST', 'GeoTIFF', 'CC-BY 4.0', 'High-resolution population grids with age/sex disaggregation', ['population','demographics'])
add('GPW v4 (SEDAC)', 'https://sedac.ciesin.columbia.edu/data/collection/gpw-v4', PU, 'population-grid', 'global', None, 'NASA SEDAC / CIESIN', 'Census-based population grids', '1km', '5-year', '2000-2020', 'free', False, None, 'GeoTIFF, NetCDF', None, 'Census-based gridded population of the world', ['population','census'])
add('LandScan Global', 'https://landscan.ornl.gov/', PU, 'population-grid', 'global', None, 'ORNL', 'Ambient population grids', '1km', 'annual', '2000-2023', 'free', False, None, 'GeoTIFF', None, 'Ambient 24-hr average population distribution, free since 2022', ['population','ambient'])
add('Meta High Resolution Population', 'https://dataforgood.facebook.com/', PU, 'population-grid', 'global', None, 'Meta', 'AI-derived population at 30m', '30m', 'single epoch', '2019-2022', 'free', False, None, 'GeoTIFF, CSV', None, 'Very high resolution population from AI building detection + census', ['population','AI','high-resolution'])
add('Microsoft Building Footprints', 'https://github.com/microsoft/GlobalMLBuildingFootprints', PU, 'building-footprints', 'global', None, 'Microsoft', 'Building footprint polygons', 'individual buildings', 'snapshot', '2023', 'free', True, 'PMTiles', 'GeoJSON, Parquet', 'ODbL', 'AI-derived building footprints for 800M+ buildings worldwide', ['buildings','footprints','AI'])
add('Google Open Buildings', 'https://sites.research.google/open-buildings/', PU, 'building-footprints', 'global', None, 'Google Research', 'Building footprints for Global South', 'individual buildings', 'snapshot', '2023', 'free', True, 'GEE, BigQuery', 'CSV, GeoJSON', 'CC-BY 4.0', '1.8B building footprints for Africa, Asia, Latin America', ['buildings','footprints','AI'])
add('VIIRS Black Marble (VNP46)', 'https://blackmarble.gsfc.nasa.gov/', PU, 'nighttime-lights', 'global', None, 'NASA', 'Calibrated nighttime lights', '500m', 'daily/monthly/annual', '2012-present', 'free', True, 'LAADS DAAC', 'HDF5, GeoTIFF', None, 'Calibrated nighttime lights from VIIRS with lunar/stray-light correction', ['nighttime-lights','radiance'])
add('DMSP-OLS Nighttime Lights', 'https://eogdata.mines.edu/', PU, 'nighttime-lights', 'global', None, 'NOAA / Colorado School of Mines', 'Historical nighttime lights', '1km', 'annual', '1992-2013', 'free', False, None, 'GeoTIFF', None, 'Historical nighttime lights archive 1992-2013', ['nighttime-lights','historical'])
add('Urban Atlas (Copernicus)', 'https://land.copernicus.eu/local/urban-atlas', PU, 'urban-lulc', 'europe', None, 'Copernicus / EEA', 'Urban land use/land cover for ~800 FUAs', '10m', 'multi-epoch', '2006-2018', 'free', False, None, 'GPKG, SHP', None, 'Detailed LULC for ~800 European functional urban areas', ['urban','land-use','cities'])
add('DEGURBA Grid (JRC)', 'https://ghsl.jrc.ec.europa.eu/degurba.php', PU, 'classification', 'global', None, 'JRC / Eurostat', 'Urban/rural settlement classification', '1km', 'census-aligned', None, 'free', False, None, 'GeoTIFF', None, 'Official EU-OECD urban-rural classification grid', ['urban-rural','classification'])
add('European Settlement Map (ESM)', 'https://ghsl.jrc.ec.europa.eu/esm.php', PU, 'built-up', 'europe', None, 'JRC', 'Very high-res built-up area', '2.5m', 'snapshot', '2015', 'free', False, None, 'GeoTIFF', None, 'Very high resolution European built-up area from SPOT + Sentinel', ['built-up','settlement'])
add('GRIP Global Roads', 'https://www.globio.info/download-grip-dataset', PU, 'infrastructure', 'global', None, 'PBL / GLOBIO', 'Global road network vectors', 'individual segments', 'snapshot', '2018', 'free', False, None, 'SHP, GeoPackage', None, '21M km of roads classified by type for accessibility modeling', ['roads','transport'])
add('WSF World Settlement Footprint (DLR)', 'https://geoservice.dlr.de/web/maps/eoc:wsf', PU, 'built-up', 'global', None, 'DLR', 'Settlement extent + evolution + 3D', '10m', 'multi-epoch', '1985-2019', 'free', True, 'WMS/WFS', 'GeoTIFF', None, 'Global settlement extent from SAR/optical with building height/volume', ['settlement','evolution','3D'])
add('Copernicus Imperviousness HRL', 'https://land.copernicus.eu/pan-european/high-resolution-layers/imperviousness', PU, 'sealed-surface', 'europe', None, 'Copernicus / EEA', 'Sealed surface fraction 0-100%', '10m', 'multi-epoch', '2006-2018', 'free', True, 'WMS', 'GeoTIFF', None, 'Imperviousness density and change for European urban expansion', ['imperviousness','sealed-surface'])
add('GHS-BUILT-H Building Height', 'https://ghsl.jrc.ec.europa.eu/ghs_buH2023.php', PU, 'building-height', 'global', None, 'JRC', 'Building height grids', '100m', 'snapshot', '2018', 'free', False, None, 'GeoTIFF', None, 'Average building height per grid cell from satellite + lidar fusion', ['building-height','3D'])
add('Kontur Population', 'https://www.kontur.io/portfolio/population-dataset/', PU, 'population-grid', 'global', None, 'Kontur', 'Population in H3 hexagons', '~460m (H3 res 8)', 'annual', '2022-2023', 'free', False, None, 'GeoPackage', None, 'Global population in H3 hexagons merging GHSL, Meta, MS, OSM', ['population','H3','hexagonal'])
add('UN World Urbanization Prospects', 'https://population.un.org/wup/', PU, 'statistics', 'global', None, 'UN DESA', 'Urban population projections', 'country/city level', 'biennial', '1950-2050', 'free', True, 'REST', 'CSV, XLSX', None, 'Urban/rural population estimates and projections by country and city', ['urbanization','projections'])
add('Eurostat GEOSTAT Population Grid', 'https://ec.europa.eu/eurostat/web/gisco/geodata/population-distribution/geostat', PU, 'population-grid', 'europe', None, 'Eurostat', 'Census population grid', '1km', 'census years', '2006-2021', 'free', True, 'GISCO REST', 'CSV, SHP', None, 'Bottom-up geocoded census population grid for EU/EFTA', ['population','census','grid'])
add('GUF Global Urban Footprint (DLR)', 'https://www.dlr.de/eoc/', PU, 'built-up', 'global', None, 'DLR', 'Urban extent from TanDEM-X SAR', '12m', 'snapshot', '2012', 'free', False, None, 'GeoTIFF', 'Research license', 'Binary urban/non-urban mask at 12m from TanDEM-X', ['urban','SAR','built-up'])

# ============ AIR QUALITY ============
AQ = 'air-quality'
add('EEA Air Quality Portal', 'https://www.eea.europa.eu/themes/air/air-quality-index', AQ, 'ground-stations', 'europe', None, 'EEA', 'Air quality station measurements', 'point (4000+ stations)', 'hourly/daily/annual', '1969-present', 'free', True, 'REST, SPARQL', 'CSV, JSON', None, 'Validated European air quality data from 4000+ stations', ['air-quality','NO2','PM2.5','PM10','O3'])
add('CAMS Atmosphere', 'https://atmosphere.copernicus.eu', AQ, 'model-reanalysis', 'global', None, 'ECMWF / Copernicus', 'Atmospheric composition models and reanalysis', '0.1-0.4 deg', 'hourly/daily', '2003-present', 'free', True, 'CDS API', 'NetCDF, GRIB', 'Copernicus License', 'Global and European atmospheric composition reanalysis and forecasts', ['atmosphere','reanalysis','forecast','aerosol'])
add('OpenAQ', 'https://openaq.org', AQ, 'ground-stations', 'global', None, 'OpenAQ', 'Aggregated air quality measurements', 'point (30,000+ locations)', 'hourly', 'varies', 'free', True, 'REST API v2/v3', 'JSON, CSV', 'CC-BY 4.0', 'Aggregated government air quality data from 100+ countries', ['air-quality','open-data','PM2.5'])
add('AQICN World Air Quality Index', 'https://aqicn.org', AQ, 'ground-stations', 'global', None, 'AQICN', 'Real-time AQI from 12,000+ stations', 'point', 'hourly', 'real-time', 'freemium', True, 'REST', 'JSON', None, 'Real-time Air Quality Index for PM2.5, PM10, O3, NO2, SO2, CO', ['AQI','real-time','air-quality'])
add('Sentinel-5P TROPOMI', 'https://s5phub.copernicus.eu', AQ, 'satellite', 'global', None, 'ESA / Copernicus', 'Atmospheric trace gas columns from satellite', '3.5x5.5 km', 'daily', '2017-present', 'free', True, 'OData', 'NetCDF', 'Copernicus License', 'NO2, O3, SO2, CO, CH4, HCHO, aerosol index from TROPOMI', ['NO2','O3','SO2','CH4','TROPOMI','satellite'])
add('EDGAR Emissions Database', 'https://edgar.jrc.ec.europa.eu', AQ, 'emission-inventory', 'global', None, 'JRC / EC', 'Gridded emission inventories', '0.1 deg', 'annual', '1970-present', 'free', False, None, 'NetCDF, Excel', None, 'Global gridded emissions of CO2, CH4, N2O, NOx, SO2, PM by sector', ['emissions','CO2','CH4','NOx','inventory'])
add('E-PRTR Industrial Emissions', 'https://industry.eea.europa.eu', AQ, 'emission-inventory', 'europe', None, 'EEA', 'Facility-level pollutant releases', 'point (30,000 facilities)', 'annual', '2007-present', 'free', True, 'SPARQL, REST', 'CSV, XML', None, 'Annual releases of 91 pollutants from European industrial facilities', ['emissions','industrial','facility-level'])
add('AERONET', 'https://aeronet.gsfc.nasa.gov', AQ, 'ground-stations', 'global', None, 'NASA', 'Aerosol optical depth from sun photometers', 'point (500+ stations)', 'sub-hourly', '1993-present', 'free', True, 'Web services', 'ASCII', None, 'Ground-based aerosol measurements from 500+ sun photometer stations', ['aerosol','AOD','sun-photometer'])
add('EMEP/EBAS', 'https://ebas.nilu.no', AQ, 'ground-stations', 'europe', None, 'NILU / UNECE', 'Atmospheric composition monitoring', 'point', 'hourly-weekly', '1970s-present', 'free', True, 'REST API', 'NASA-Ames, CSV', None, 'European background atmospheric composition monitoring (aerosol, gases, precip chemistry)', ['atmospheric-composition','background','EMEP'])
add('Climate TRACE', 'https://climatetrace.org', AQ, 'emission-inventory', 'global', None, 'Climate TRACE Coalition', 'Satellite-derived facility-level emissions', 'facility-level', 'annual', '2015-present', 'free', True, 'REST API', 'CSV, JSON, GeoJSON', 'CC-BY 4.0', 'Independent satellite-based GHG emission verification by sector', ['emissions','GHG','satellite-derived'])
add('Hungarian OLM Air Quality', 'https://legszennyezettseg.met.hu', AQ, 'ground-stations', 'national', 'HU', 'HungaroMet / OMSZ', 'Hungarian air quality monitoring', 'point (~30 stations)', 'hourly', 'varies', 'free', False, None, 'CSV', None, 'Hungarian national air quality monitoring network', ['air-quality','Hungary'])
add('TOAR Ozone Database', 'https://toar-data.org', AQ, 'ground-stations', 'global', None, 'FZ Juelich', 'Harmonized global surface ozone', 'point (10,000 stations)', 'hourly/metrics', 'varies', 'free', True, 'REST API', 'JSON, CSV', None, 'Harmonized global surface ozone and related metrics from 10,000 stations', ['ozone','surface','harmonized'])
add('ICOS Carbon Observatory', 'https://www.icos-cp.eu', AQ, 'ground-stations', 'europe', None, 'ICOS ERIC', 'High-precision GHG measurements', 'point (~140 stations)', 'sub-hourly', '2015-present', 'free', True, 'SPARQL, REST', 'NetCDF, CSV', 'CC-BY 4.0', 'Research-grade CO2, CH4, N2O flux and concentration measurements', ['CO2','CH4','N2O','flux','carbon'])
add('ACTRIS Data Centre', 'https://actris.nilu.no', AQ, 'ground-stations', 'europe', None, 'ACTRIS', 'Aerosol, cloud, trace gas properties', 'point (~100 stations)', 'minutes-daily', 'varies', 'free', True, 'REST API', 'NetCDF, NASA-Ames', None, 'European aerosol physical/chemical/optical and cloud properties', ['aerosol','cloud','trace-gas'])
add('Sensor.Community (Luftdaten)', 'https://sensor.community', AQ, 'citizen-science', 'global', None, 'Sensor.Community', 'Citizen science low-cost PM sensors', 'point (15,000+ sensors)', '~2.5 min', 'varies', 'free', True, 'REST API', 'CSV, JSON', 'Open Data', 'Citizen science PM2.5/PM10 network with strong Central European coverage', ['citizen-science','low-cost','PM2.5'])
add('PurpleAir', 'https://www2.purpleair.com', AQ, 'citizen-science', 'global', None, 'PurpleAir', 'Low-cost PM sensor network', 'point (tens of thousands)', 'real-time (2 min)', 'varies', 'free', True, 'REST API', 'JSON', None, 'Community low-cost PM sensor network, mostly USA', ['citizen-science','low-cost','PM2.5'])
add('S5P-PAL Data Portal', 'https://data-portal.s5p-pal.com', AQ, 'satellite', 'global', None, 'S5P-PAL / DLR', 'Pre-processed gridded TROPOMI data', '0.01-0.05 deg', 'daily/weekly/monthly', '2018-present', 'free', False, None, 'GeoTIFF, NetCDF', None, 'Easy-to-use pre-processed gridded TROPOMI NO2, O3, SO2, CO, CH4', ['TROPOMI','gridded','pre-processed'])
add('CIESIN PM2.5 Grids (SEDAC)', 'https://sedac.ciesin.columbia.edu', AQ, 'satellite-derived', 'global', None, 'NASA SEDAC', 'Global gridded PM2.5 and NO2', '0.01 deg', 'annual', '1998-present', 'free', False, None, 'GeoTIFF, NetCDF', None, 'Global annual PM2.5 and NO2 grids widely used in health studies', ['PM2.5','NO2','health','gridded'])
add('GFED Global Fire Emissions', 'https://www.globalfiredata.org', AQ, 'emission-inventory', 'global', None, 'GFED Team', 'Fire emission inventories', '0.25 deg', 'monthly/daily', '1997-present', 'free', False, None, 'HDF5', None, 'CO2, CO, CH4, NOx, PM2.5, BC from biomass burning + burned area', ['fire','emissions','biomass-burning'])
add('TEMIS', 'https://www.temis.nl', AQ, 'satellite', 'global', None, 'KNMI / ESA', 'Processed satellite trace gas L3 products', '0.125-0.25 deg', 'daily/monthly', '1995-present', 'free', False, None, 'ASCII, HDF', None, 'Long time series of NO2, O3, SO2, UV index from multiple satellite sensors', ['NO2','O3','UV','satellite','long-term'])
add('WHO Air Quality Database', 'https://www.who.int/data/gho/data/themes/air-pollution', AQ, 'statistics', 'global', None, 'WHO', 'City-level annual mean PM2.5/PM10', 'city level (6,000+ cities)', 'annual', 'varies', 'free', False, None, 'Excel, CSV', None, 'Annual mean PM2.5 and PM10 for cities worldwide', ['PM2.5','PM10','cities','health'])
add('US EPA AirNow', 'https://www.airnow.gov', AQ, 'ground-stations', 'national', 'US', 'US EPA', 'Real-time US air quality', 'point (~2,000 monitors)', 'hourly', 'real-time', 'free', True, 'REST API', 'JSON, CSV, KML', None, 'Real-time AQI and fire/smoke maps for USA', ['AQI','real-time','USA'])
add('German UBA Air Quality', 'https://www.umweltbundesamt.de/daten/luft/luftdaten', AQ, 'ground-stations', 'national', 'DE', 'Umweltbundesamt', 'German air quality network', 'point (~500 stations)', 'hourly', 'varies', 'free', True, 'REST API', 'CSV', None, 'German national air quality monitoring from federal + Laender networks', ['air-quality','Germany'])
add('Polish GIOS Air Quality', 'https://powietrze.gios.gov.pl', AQ, 'ground-stations', 'national', 'PL', 'GIOS', 'Polish air quality network', 'point (~250 stations)', 'hourly', 'varies', 'free', True, 'REST API', 'JSON', None, 'Polish national air quality monitoring including BaP', ['air-quality','Poland'])
add('European Pollen Network', 'https://www.polleninfo.org', AQ, 'pollen', 'europe', None, 'EAN', 'Pollen concentration monitoring', 'point (network stations)', 'daily/weekly', 'seasonal', 'free', False, None, None, None, 'European pollen concentration monitoring and forecasts by taxon', ['pollen','allergen','ragweed'])

# ============ OCEAN / MARINE ============
OM = 'ocean-marine'
add('GEBCO', 'https://www.gebco.net', OM, 'bathymetry', 'global', None, 'GEBCO / IHO / IOC', 'Global ocean bathymetry', '15 arc-sec (~450m)', 'periodic updates', '2023', 'free', True, 'WMS/WCS', 'NetCDF, GeoTIFF', 'CC-BY 4.0', 'General Bathymetric Chart of the Oceans - global seafloor topography', ['bathymetry','ocean-floor','depth'])
add('NOAA ETOPO', 'https://www.ncei.noaa.gov/products/etopo-global-relief-model', OM, 'bathymetry', 'global', None, 'NOAA NCEI', 'Combined bathymetry + topography', '15 arc-sec', 'periodic', '2022', 'free', True, 'THREDDS/OPeNDAP', 'NetCDF, GeoTIFF', 'Public domain', 'Global relief model combining ocean bathymetry and land topography', ['bathymetry','topography','relief'])
add('EMODnet Bathymetry', 'https://emodnet.ec.europa.eu/en/bathymetry', OM, 'bathymetry', 'europe', None, 'EMODnet / EU', 'European marine bathymetry', '~115m (1/16 arc-min)', 'periodic', 'latest', 'free', True, 'WMS/WCS/REST', 'NetCDF, ASCII, GeoTIFF', None, 'High-resolution European seabed DTM with source survey data', ['bathymetry','Europe','seabed'])
add('Copernicus Marine (CMEMS)', 'https://marine.copernicus.eu', OM, 'multi-domain', 'global', None, 'Mercator Ocean / EU', 'SST, currents, salinity, sea level, waves, biogeochem', '1/12 to 1/48 deg', 'hourly-monthly', '1993-present', 'free', True, 'Python API, OPeNDAP, WMS', 'NetCDF, Zarr', 'Copernicus License', 'Comprehensive ocean analysis, forecast, and reanalysis for global and European seas', ['ocean','SST','currents','waves','sea-level','reanalysis'])
add('NASA PO.DAAC', 'https://podaac.jpl.nasa.gov', OM, 'satellite-oceanography', 'global', None, 'NASA JPL', 'Sea level, SST, ocean winds, salinity', '1-25 km', 'daily-monthly', 'varies', 'free', True, 'OPeNDAP, CMR API', 'NetCDF, HDF5', None, 'Physical oceanography satellite data archive (altimetry, SST, salinity)', ['ocean','SST','altimetry','salinity','satellite'])
add('NASA Ocean Color (OB.DAAC)', 'https://oceancolor.gsfc.nasa.gov', OM, 'satellite-oceanography', 'global', None, 'NASA GSFC', 'Ocean color, chlorophyll, water quality', '300m-1km', 'daily', 'varies', 'free', True, 'OPeNDAP, CMR', 'HDF5, NetCDF', None, 'Satellite-derived ocean color and chlorophyll from MODIS, VIIRS, PACE', ['ocean-color','chlorophyll','water-quality'])
add('Argo Float Network', 'https://argo.ucsd.edu', OM, 'in-situ', 'global', None, 'International Argo Program', 'Temperature/salinity profiles 0-2000m', '~3 deg spacing', '10-day cycle', '2000-present', 'free', True, 'ERDDAP, FTP', 'NetCDF', None, 'Global network of ~4000 autonomous profiling floats measuring T/S', ['ocean','temperature','salinity','profiles','floats'])
add('OBIS', 'https://obis.org', OM, 'biodiversity', 'global', None, 'UNESCO-IOC', 'Marine species occurrences', 'point records', 'continuous', 'varies', 'free', True, 'REST API', 'Darwin Core', None, 'Ocean Biodiversity Information System with 100M+ marine species records', ['marine-biodiversity','species','occurrences'])
add('PSMSL Tide Gauges', 'https://www.psmsl.org', OM, 'sea-level', 'global', None, 'PSMSL / NOC', 'Long-term tide gauge records', 'point (~1500 stations)', 'monthly/annual', '1800s-present', 'free', True, 'data download', 'ASCII', None, 'Permanent Service for Mean Sea Level - long-term sea level records', ['sea-level','tide-gauge','long-term'])
add('IOC Sea Level Monitoring', 'https://www.ioc-sealevelmonitoring.org', OM, 'sea-level', 'global', None, 'IOC-UNESCO', 'Real-time tide gauge data', 'point (~1000 stations)', 'minutes', 'real-time', 'free', True, 'JSON API', 'JSON', None, 'Real-time tide gauge monitoring from ~1000 operational stations', ['sea-level','real-time','tide-gauge'])
add('AVISO+ Altimetry', 'https://www.aviso.altimetry.fr', OM, 'satellite-altimetry', 'global', None, 'CNES / CLS', 'Satellite altimetry, sea level anomaly', '0.25 deg', 'daily', 'varies', 'free', True, 'FTP, OPeNDAP', 'NetCDF', None, 'Gridded sea level anomalies and along-track altimetry data', ['altimetry','sea-level','satellite'])
add('SeaDataNet', 'https://www.seadatanet.org', OM, 'aggregator', 'europe', None, 'SeaDataNet Consortium', 'Pan-European aggregated ocean data', 'profile/time-series', 'varies', 'varies', 'free', True, 'CDI search', 'ODV, NetCDF', None, 'Aggregated oceanographic data from 100+ European data centres', ['ocean','aggregator','Europe','CTD'])
add('SOCAT Surface Ocean CO2', 'https://www.socat.info', OM, 'ocean-chemistry', 'global', None, 'SOCAT Community', 'Surface ocean CO2 measurements', 'point (ship tracks)', 'varies', '1957-present', 'free', True, 'ERDDAP', 'TSV, NetCDF', None, 'Surface Ocean CO2 Atlas with 30M+ fCO2 observations', ['CO2','ocean-carbon','surface'])
add('EMODnet Biology', 'https://emodnet.ec.europa.eu/en/biology', OM, 'biodiversity', 'europe', None, 'EMODnet / EU', 'Marine species distributions', 'point/grid', 'varies', 'varies', 'free', True, 'WFS/WMS/ERDDAP', 'NetCDF, SHP', None, 'European marine species distribution and gridded abundance products', ['marine-biology','species','Europe'])
add('EMODnet Geology', 'https://emodnet.ec.europa.eu/en/geology', OM, 'seabed', 'europe', None, 'EMODnet / EU', 'Seabed substrate, geology, coastal erosion', '1:250k-1:1M', 'static', 'latest', 'free', True, 'WMS/WFS', 'SHP, GeoPackage', None, 'European seabed substrate, sea-floor geology, and coastal behavior', ['seabed','geology','substrate','coastal'])
add('HELCOM Map Service', 'https://maps.helcom.fi', OM, 'regional', 'regional', None, 'HELCOM', 'Baltic Sea environmental monitoring', 'station/grid', 'varies', 'varies', 'free', True, 'WMS/WFS', 'GIS formats', None, 'Baltic Sea eutrophication, hazardous substances, biodiversity indicators', ['Baltic','environmental','monitoring'])
add('OSPAR Data Information', 'https://odims.ospar.org', OM, 'regional', 'regional', None, 'OSPAR Commission', 'NE Atlantic environmental monitoring', 'station', 'varies', 'varies', 'free', True, 'WMS/WFS', 'GIS formats', None, 'NE Atlantic contaminants, eutrophication, biodiversity assessments', ['Atlantic','environmental','monitoring'])
add('Global Fishing Watch', 'https://globalfishingwatch.org', OM, 'human-activity', 'global', None, 'Global Fishing Watch', 'Fishing vessel activity tracking', '~0.01 deg', 'daily', '2012-present', 'free', True, 'REST/BigQuery', 'CSV, GeoJSON', 'CC-BY-NC', 'Global fishing effort, vessel identity, and marine use monitoring', ['fishing','vessel','AIS','marine'])
add('WOD World Ocean Database', 'https://www.ncei.noaa.gov/products/world-ocean-database', OM, 'in-situ', 'global', None, 'NOAA NCEI', 'Ocean temperature/salinity/nutrient profiles', 'profiles', 'varies', '1770s-present', 'free', True, 'WODselect', 'NetCDF, CSV', 'Public domain', 'Largest international ocean profile database (T, S, O2, nutrients)', ['ocean-profiles','temperature','nutrients'])

# ============ ADMIN BOUNDARIES (supplement) ============
AB = 'admin-boundaries'
add('geoBoundaries', 'https://www.geoboundaries.org', AB, 'admin-boundaries', 'global', None, 'William & Mary', 'Standardized admin boundaries', 'levels 0-5', 'static', 'latest', 'free', True, 'REST', 'GeoJSON', 'CC-BY 4.0', 'Standardized global admin boundaries with open and authoritative versions', ['admin','boundaries','open-data'])
add('UN SALB', 'https://salb.un.org', AB, 'admin-boundaries', 'global', None, 'United Nations', 'UN-endorsed admin boundaries', 'levels 0-2', 'static', 'latest', 'free', False, None, 'SHP', None, 'Official UN second administrative level boundaries', ['admin','boundaries','UN'])
add('HDX Humanitarian Data Exchange', 'https://data.humdata.org', AB, 'humanitarian', 'global', None, 'OCHA', 'Humanitarian datasets + COD admin boundaries', 'varies', 'varies', 'varies', 'free', True, 'CKAN API', 'SHP, GeoJSON, CSV', None, 'Common Operational Datasets including admin boundaries for humanitarian use', ['humanitarian','admin','boundaries','COD'])
add('GeoNames', 'https://www.geonames.org', AB, 'gazetteer', 'global', None, 'GeoNames', 'Place names and geocoding', 'point (12M+ names)', 'continuous', 'daily updates', 'free', True, 'REST', 'CSV, XML', 'CC-BY 4.0', 'Global gazetteer with 12M+ place names, postal codes, and elevation', ['place-names','geocoding','postal-codes'])
add('Overture Maps', 'https://overturemaps.org', AB, 'multi-domain', 'global', None, 'Linux Foundation', 'Buildings, places, transport, admin boundaries', 'individual features', 'quarterly', '2023-present', 'free', True, 'S3, Azure, DuckDB', 'GeoParquet', 'CDLA Permissive 2.0', 'Merged vector data (buildings, roads, places, admin) in cloud-native format', ['buildings','roads','admin','cloud-native'])
add('Eurostat GISCO', 'https://ec.europa.eu/eurostat/web/gisco', AB, 'reference', 'europe', None, 'Eurostat', 'NUTS/LAU/communes, reference grids, coastlines', 'NUTS 0-3, LAU', 'annual', 'latest', 'free', True, 'REST, WMS, WFS', 'SHP, GeoJSON, TopoJSON', None, 'Official EU statistical boundaries (NUTS, LAU), population grids, urban audit', ['NUTS','LAU','statistics','Europe'])
add('INSPIRE Geoportal', 'https://inspire-geoportal.ec.europa.eu', AB, 'multi-theme', 'europe', None, 'EU / EC', 'Harmonized spatial data across 34 INSPIRE themes', 'varies by country', 'varies', 'varies', 'free', True, 'WMS, WFS, ATOM', 'GML', None, 'EU directive harmonized spatial data including cadastral, transport, hydro, protected sites', ['INSPIRE','cadastral','harmonized','EU'])
add('Netherlands PDOK', 'https://www.pdok.nl', AB, 'national-sdi', 'national', 'NL', 'Kadaster / PDOK', 'Dutch reference data (addresses, buildings, cadastral, topo)', 'parcel-level', 'continuous', 'latest', 'free', True, 'WMS, WFS, WCS, OGC API', 'GeoJSON, GML, GeoPackage', None, 'One of the best national SDIs: BAG, BRK, BGT, BRT, AHN', ['Netherlands','cadastral','addresses','buildings'])
add('Poland GUGiK Geoportal', 'https://mapy.geoportal.gov.pl', AB, 'national-sdi', 'national', 'PL', 'GUGiK', 'Polish cadastral, topo, ortho, DEM', 'parcel-level', 'continuous', 'latest', 'free', True, 'WMS, WFS, WMTS', 'GML, SHP', None, 'Comprehensive Polish geoportal with cadastral, topo, ortho, NMT open data', ['Poland','cadastral','topo','ortho'])
add('Switzerland swisstopo', 'https://www.swisstopo.admin.ch', AB, 'national-sdi', 'national', 'CH', 'swisstopo', 'Swiss reference data, topo, cadastral, aerial', 'parcel-level to 1:25k', 'continuous', 'latest', 'free', True, 'REST, WMS, WMTS', 'multiple', None, 'Swiss national mapping: swissBOUNDARIES3D, swissTLM3D, cadastral, topo, aerial (free since 2021)', ['Switzerland','cadastral','topo','aerial'])
add('Norway Geonorge', 'https://www.geonorge.no', AB, 'national-sdi', 'national', 'NO', 'Kartverket', 'Norwegian reference data', 'high detail', 'continuous', 'latest', 'free', True, 'WMS, WFS, WCS, OGC API', 'multiple', 'CC-BY 4.0 / NLOD', 'Norwegian national SDI with admin, cadastral, topo, elevation, place names', ['Norway','cadastral','topo','admin'])
add('Czech Republic CUZK', 'https://geoportal.cuzk.cz', AB, 'national-sdi', 'national', 'CZ', 'CUZK', 'Czech cadastral, topo, ortho', 'parcel-level', 'continuous', 'latest', 'free', True, 'WMS, WFS', 'GML, SHP', 'CC-BY 4.0', 'Czech national geoportal: RUIAN register, orthophotos, topo (all open since 2023)', ['Czech','cadastral','RUIAN','open-data'])
add('Spain INSPIRE Cadastre', 'https://www.sedecatastro.gob.es', AB, 'cadastral', 'national', 'ES', 'Catastro', 'Spanish cadastral parcels', 'parcel-level', 'continuous', 'latest', 'free', True, 'WMS, WFS, ATOM', 'GML', None, 'One of the best INSPIRE cadastral implementations in Europe', ['Spain','cadastral','INSPIRE'])
add('France data.gouv.fr', 'https://www.data.gouv.fr', AB, 'national-sdi', 'national', 'FR', 'IGN / Etalab', 'French admin boundaries, cadastral, topo', 'all levels', 'continuous', 'latest', 'free', True, 'REST, WMS, WFS', 'GeoJSON, SHP, GeoPackage', 'Open License', 'French open data portal with communes, departments, regions, cadastral, BD TOPO', ['France','cadastral','admin','open-data'])
add('Lechner Tudaskozpont', 'https://lfrankl.lechnerkozpont.hu', AB, 'national-sdi', 'national', 'HU', 'Lechner Tudaskozpont', 'Hungarian cadastral, topo, ortho', 'parcel-level', 'continuous', 'latest', 'freemium', True, 'WMS, WFS', 'SHP, GeoJSON', None, 'Hungarian national mapping agency: cadastral parcels, topo maps, orthophotos, DTM', ['Hungary','cadastral','topo','ortho'])
add('Who\'s on First', 'https://www.whosonfirst.org', AB, 'gazetteer', 'global', None, 'Mapzen / Linux Foundation', 'Hierarchical place gazetteer', 'neighbourhood to country', 'continuous', 'latest', 'free', True, 'REST, SQLite', 'GeoJSON', 'CC-BY 4.0', 'Hierarchical place gazetteer with stable IDs, neighbourhood-level detail', ['gazetteer','places','hierarchy'])
add('OpenAddresses', 'https://openaddresses.io', AB, 'addresses', 'global', None, 'OpenAddresses', 'Aggregated official address points', 'address-point level', 'varies', 'latest', 'free', True, 'batch download', 'CSV', None, 'Aggregated address points with coordinates from authoritative sources', ['addresses','geocoding','open-data'])
add('EEA Reference Grids', 'https://www.eea.europa.eu/data-and-maps/data/eea-reference-grids-2', AB, 'reference-grid', 'europe', None, 'EEA', 'European standard reporting grids', '1km, 10km, 100km', 'static', 'latest', 'free', False, None, 'SHP', None, 'EEA ETRS89-LAEA reference grids used for CORINE, population, species distribution', ['grid','reference','ETRS89','reporting'])

# Sort and write
data.sort(key=lambda x: x['name'].lower())
with open('C:/DatasetCadaster/datasets.json', 'w', encoding='utf-8') as f:
    json.dump(data, f, indent=2, ensure_ascii=False)

# Count categories
cats = {}
for e in data:
    cats[e['category']] = cats.get(e['category'], 0) + 1
print(f'\nTotal: {len(data)} entries')
for k, v in sorted(cats.items(), key=lambda x: -x[1]):
    print(f'  {k}: {v}')
